In [70]:
import scipy.optimize
from scipy.optimize import minimize

In [71]:
def F(x, q1, q2, q3, q4, q5, q6, q7, q8, q9):
    r1, r2, r3, r4, r5, r6, r7, r8, r9 = x
    return q1 * r1 + q2 * r2 + q3 * r3 + q4 * r4 + q5 * r5 + q6 * r6 + q7 * r7 + q8 * r8 + q9 * r9

def constraint1(x):
    r1, r2, r3, r4, r5, r6, r7, r8, r9 = x
    return r1, r2, r3, r4, r5, r6, r7, r8, r9

def constraint2(x, q1, q2, q3, q4, q5, q6, q7, q8, q9):
    return 1459317 - (q1*x[0] + q2*x[1] + q3*x[2] + q4*x[3] + q5*x[4] + q6*x[5] + q7*x[6] + q8*x[7] + q9*x[8])

In [72]:
q1 = 31200
q2 = 22550.64
q3 = 51200
q4 = 42282
q5 = 65000
q6 = 89564
q7 = 6000
q8 = 24664.5
q9 = 4000

x0 = [0.12, 0.18, 0.16, 0.15, 0.1, 0.1, 0.1, 0.05, 0.04]

In [73]:
bound = scipy.optimize.Bounds(lb=0.001, ub=1)

cons = [{'type': 'ineq', 'fun': constraint1}, 
        {'type': 'ineq', 'fun': constraint2, 'args': (q1, q2, q3, q4, q5, q6, q7, q8, q9)}]

In [74]:
res = minimize(F, x0, args=(q1, q2, q3, q4, q5, q6, q7, q8, q9), bounds=bound, constraints=cons)
res.x

array([0.03707101, 0.02707104, 0.06019335, 0.04988296, 0.07614789,
       0.10454691, 0.00793662, 0.02951511, 0.00562444])

In [75]:
sum(res.x)

0.3979893274645291

In [76]:
def F2(x, q):
    r1, r2, r3, r4, r5, r6, r7, r8, r9 = x
    q1, q2, q3, q4, q5, q6, q7, q8, q9 = q
    return q1 * r1 + q2 * r2 + q3 * r3 + q4 * r4 + q5 * r5 + q6 * r6 + q7 * r7 + q8 * r8 + q9 * r9

In [77]:
bound2 = scipy.optimize.Bounds(lb=1)

cons2 = [{'type': 'ineq', 'fun': constraint1}, {'type': 'ineq', 'fun': constraint2, 'args': res.x}]

In [78]:
res2 = minimize(F2, x0=(q1, q2, q3, q4, q5, q6, q7, q8, q9), args=res.x, bounds=bound2, constraints=cons2)

In [79]:
res2.x

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
import numpy as np

X = np.arange(-2, 2, 0.1)
Y = np.arange(-1, 3, 0.1)
X, Y = np.meshgrid(X, Y)

In [81]:
X

array([[-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
       [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
       [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
       ...,
       [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
       [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
       [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9]])

In [82]:
Y

array([[-1. , -1. , -1. , ..., -1. , -1. , -1. ],
       [-0.9, -0.9, -0.9, ..., -0.9, -0.9, -0.9],
       [-0.8, -0.8, -0.8, ..., -0.8, -0.8, -0.8],
       ...,
       [ 2.7,  2.7,  2.7, ...,  2.7,  2.7,  2.7],
       [ 2.8,  2.8,  2.8, ...,  2.8,  2.8,  2.8],
       [ 2.9,  2.9,  2.9, ...,  2.9,  2.9,  2.9]])

In [83]:
np.array([X,Y])

array([[[-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
        [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
        [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
        ...,
        [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
        [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9],
        [-2. , -1.9, -1.8, ...,  1.7,  1.8,  1.9]],

       [[-1. , -1. , -1. , ..., -1. , -1. , -1. ],
        [-0.9, -0.9, -0.9, ..., -0.9, -0.9, -0.9],
        [-0.8, -0.8, -0.8, ..., -0.8, -0.8, -0.8],
        ...,
        [ 2.7,  2.7,  2.7, ...,  2.7,  2.7,  2.7],
        [ 2.8,  2.8,  2.8, ...,  2.8,  2.8,  2.8],
        [ 2.9,  2.9,  2.9, ...,  2.9,  2.9,  2.9]]])

In [84]:
#q = np.array([31200, 22550.64, 51200, 42282, 65000, 89564, 6000, 24664.5, 4000])
#r = np.array([0.12, 0.18, 0.16, 0.15, 0.1, 0.1, 0.1, 0.05, 0.04])

def F5(r):
    q = np.array([31200, 22550.64, 51200, 42282, 65000, 89564, 6000, 24664.5, 4000])
    return np.sum(q * r, axis=0)

In [85]:
F5(np.array([0.12, 0.18, 0.16, 0.15, 0.1, 0.1, 0.1, 0.05, 0.04]))

39787.0402

In [86]:
q[0] * r[0] + q[1] * r[1] + q[2] * r[2] + q[3] * r[3] + q[4] * r[4] + q[5] * r[5] + q[6] * r[6] + q[7] * r[7] + q[8] * r[8]

39787.040199999996

In [87]:
r = np.array([0.12, 0.18, 0.16, 0.15, 0.1, 0.1, 0.1, 0.05, 0.04])
bound5 = scipy.optimize.Bounds(lb=0.001, ub=1)

res5 = minimize(F5, r, method='nelder-mead', bounds=bound5)
print(res5.x)

[0.00101835 0.00146898 0.00114722 0.00111003 0.00114792 0.00114356
 0.001      0.00138486 0.00210715]
